title: CMake XCommon
project: cmake_xcommon
version: 1.0.0
exclude_patterns_path: .doc_exclude
documentation:
    pdfs:
        index:
            pdf_title: "CMake XCommon"
            pdf_filename: "cmake_xcommon"
