title: XCommon CMake
project: xcommon_cmake
version: 0.1.0
exclude_patterns_path: .doc_exclude
documentation:
    pdfs:
        index:
            pdf_title: "XCommon CMake"
            pdf_filename: "xcommon_cmake"
